### ISSUE TITLE
Background color for authorization pages

### ISSUE THREAD

**Issue by Ajnasz** [digitalocean/api-v2#103]
Hi!

This bug is not really related to the API, but the authorization pages.
When the browser's default background color is not white, the authorization pages  background will not be white. Starting from the https://cloud.digitalocean.com/login page, the https://cloud.digitalocean.com/login/tfa and where you grant access, all pages has the browser's default background color.
It's a problem, if I want to create a Firefox OS application.

You can test it by using some user style in your browser (for example by using stylish) like the following code:

``` css
@namespace url(http://www.w3.org/1999/xhtml);
@-moz-document domain("cloud.digitalocean.com") {
    html {
        background-color: #ff0;
    }
}
```

I would suggest to set a white background color for all pages under cloud.digitalocean.com.

Thanks!
