### ISSUE TITLE
Creating CoreOS Droplet: returns success, but Droplet never shows up

### ISSUE THREAD

**Issue by blakelapierre** [digitalocean/api-v2#90]
I'm calling:

```
curl -X POST "https://api.digitalocean.com/v2/droplets" \
      -d'{"name":"coreos-5","region":"sfo1","size":"512mb","image":"coreos-alpha","user_data":
"#cloud-config

coreos:
  etcd:
    discovery: https://discovery.etcd.io/<id_removed>
    addr: $public_ipv4:4001
    peer-addr: $public_ipv4:7001
  fleet:
    public-ip: $public_ipv4
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start

ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDQIwGRmmZKxKiZyWRkGk95wBUuhmyitOfJQBlhLeL7n0qDxueU+oxRH3swrWYbHY8daOAKhlzQmpqAQSoFiLzdK0N5aDRyv5U01wvzRuWbQ3Fk/2iwOUzJx2y/rDVd3NbF26EBTS+7mS2n319r1TNYsuekzMD+VpZBFymcqttoOlgNnuecytpMFj18YuB3muGRgiAWZHx0md1e3/bVuVK16VEJ8MKFPWBsRiZ667gzW5b88XZO4Zvo/wAQgp6vakMaLOinxOt0IhfsVNU/miFd0AMBPq04s+iSApxBvQ/+DbBphQT4bRfgI8w8QgfwO8Hwz4MpojeAk2Dhsvmupyp blakelapierre@gmail.com","ssh_keys":["blake-desktop"]}' \
      -H "Authorization: Bearer <api_key_removed>" \
      -H "Content-Type: application/json"
```

This is the response I get back:

```
HTTP/1.1 202 Accepted
Server: cloudflare-nginx
Date: Thu, 18 Sep 2014 05:33:20 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: __cfduid=d66c74afd3c55aaeac098c439ba4552881411018399380; expires=Mon, 23-Dec-2019 23:50:00 GMT; path=/; domain=.digitalocean.com; HttpOnly
Status: 202 Accepted
RateLimit-Limit: 1200
RateLimit-Remaining: 1191
RateLimit-Reset: 1411018590
Cache-Control: no-cache
X-Request-Id: 029d7e32cc6ab0580cc9cf1ec511eab5
X-Runtime: 0.388426
X-Rack-Cache: invalidate, pass
CF-RAY: 16bb2b0421e611d1-SJC

{
  "droplet":{
    "id":2648577,
    "name":"coreos-5",
    "memory":512,
    "vcpus":1,
    "disk":20,
    "region":{
      "slug":"sfo1",
      "name":"San Francisco 1",
      "sizes":[
        "2gb",
        "4gb",
        "8gb",
        "1gb",
        "16gb",
        "32gb",
        "48gb",
        "512mb",
        "64gb"
      ],
      "available":true,
      "features":[
        "virtio",
        "backups",
        "metadata"
      ]
    },
    "image":{
      "id":6100563,
      "name":"CoreOS 440.0.0 (alpha)",
      "distribution":"CoreOS",
      "slug":"coreos-alpha",
      "public":true,
      "regions":[
        "sfo1",
        "sgp1",
        "lon1",
        "nyc3",
        "ams3"
      ],
      "created_at":"2014-09-15T22:36:43Z"
    },
    "size":{
      "slug":"512mb",
      "transfer":1,
      "price_monthly":5.0,
      "price_hourly":0.00744
    },
    "locked":true,
    "status":"new",
    "networks":{},
    "kernel":null,
    "created_at":"2014-09-18T05:33:19Z",
    "features":[
      "virtio"
    ],
    "backup_ids":[],
    "snapshot_ids":[]
  },
  "links":{
    "actions":[
      {
        "id":32667692,
        "rel":"create",
        "href":"http://api.digitalocean.com/v2/actions/32667692"
      }
    ]
  }
}
```

Looks like a successful creation, right? But it never shows up in my account. Neither in the Control Panel, or when calling the API to list all my Droplets.

I've tried nyc3 and sfo1.

Passing the equivalent setup into the DigitalOcean Control Panel page for creating the Droplet works fine.

Also, creating non-CoreOS Droplets using the API works fine for me:

```
curl -X POST "https://api.digitalocean.com/v2/droplets" \
    -d'{"name":"My-Droplet2","region":"nyc3","size":"512mb","image":5141286, "ssh_keys":["blake-desktop"]}' \
    -H "Authorization: Bearer <api_key_removed>" \
    -H "Content-Type: application/json"
```
